Name:           ros-hydro-pr2-surrogate
Version:        0.0.4
Release:        0%{?dist}
Summary:        ROS pr2_surrogate package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-actionlib
Requires:       ros-hydro-audio-capture
Requires:       ros-hydro-audio-play
Requires:       ros-hydro-geometry-msgs
Requires:       ros-hydro-image-transport-plugins
Requires:       ros-hydro-oculus-rviz-plugins
Requires:       ros-hydro-openni-camera
Requires:       ros-hydro-pr2-apps
Requires:       ros-hydro-pr2-controller-manager
Requires:       ros-hydro-pr2-controllers-msgs
Requires:       ros-hydro-razer-hydra
Requires:       ros-hydro-robot-mechanism-controllers
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rviz
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-tf
BuildRequires:  boost-devel
BuildRequires:  ros-hydro-actionlib
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-geometry-msgs
BuildRequires:  ros-hydro-pr2-controllers-msgs
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-sensor-msgs

%description
The pr2_surrogate package allows you to make a PR2 into a surrogate for your
physical body using the Oculus RIFT HMD and Razer Hydra controller.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Sun Sep 07 2014 David Gossow <dgossow@willowgarage.com> - 0.0.4-0
- Autogenerated by Bloom

